### ISSUE TITLE
Problems with path include in model.js

### ISSUE THREAD

**Issue by janrg** [naturalatlas/geomagnetism#3]
The first line of model.js is
`var path = require('path');`
As far as I can tell, it isn't actually used anywhere in there and when I tried to include geomagnetism in an ionic framework project, it first gave me errors about `path` not being available and when I npm installed that, it complained about `process` (which I couldn't fix by npm install-ing `process`). Unless there's a reason for the require to be there that I'm missing, I think it would make sense to remove that line.

**Comment by yelabb** [comment]
@janrg here is a fork that works well with ionic and Expo:
https://github.com/yelabbassi/geomagnetism

You can also just remove _path_ and replace fs by _[graceful-fs](https://github.com/isaacs/node-graceful-fs)_.

**Comment by YOEL311** [comment]
this problem also in react native without expo

**Comment by matthias-ccri** [comment]
https://github.com/naturalatlas/geomagnetism/pull/6

**Comment by matthias-ccri** [comment]
PR: https://github.com/naturalatlas/geomagnetism/pull/6

**Comment by brianreavis** [comment]
This is fixed in [0.1.1](https://github.com/naturalatlas/geomagnetism/releases/tag/v0.1.1). Thanks @matthias-ccri!
