### ISSUE TITLE
Could not find a declaration file for module 'geomagnetism'. 

### ISSUE THREAD

**Issue by xnior** [naturalatlas/geomagnetism#7]
After npm install in Angular the system says.
Could not find a declaration file for module 'geomagnetism'. 'node_modules/geomagnetism/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/geomagnetism` if it exists or add a new declaration (.d.ts) file containing `declare module 'geomagnetism';`

The error occur when try to import.
`import * as geomagnetism from 'geomagnetism';``

**Comment by xnior** [comment]
I found the error just the developer to:
`declare module "geomagnetism"`

> After npm install in Angular the system says. Could not find a declaration file for module 'geomagnetism'. 'node_modules/geomagnetism/index.js' implicitly has an 'any' type. Try `npm i --save-dev @types/geomagnetism` if it exists or add a new declaration (.d.ts) file containing `declare module 'geomagnetism';`
> 
> The error occur when try to import. `import * as geomagnetism from 'geomagnetism';``

**Comment by brianreavis** [comment]
Typescript definitions were just added in https://github.com/naturalatlas/geomagnetism/pull/9
